// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcn-sT6nYRDyjKIW95_xnGxaU0o08ZFE',
    appId: '1:429944027179:web:aaab627e23053dbb14526e',
    messagingSenderId: '429944027179',
    projectId: 'music-kuy-app',
    authDomain: 'music-kuy-app.firebaseapp.com',
    storageBucket: 'music-kuy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAER-olDsiZwyQp-z3ssMNs0Rg0A2izAhg',
    appId: '1:429944027179:android:59b7ffd13894780614526e',
    messagingSenderId: '429944027179',
    projectId: 'music-kuy-app',
    storageBucket: 'music-kuy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0kZJbZpLj3BH5JB7KmUIjudSxHkIWKiY',
    appId: '1:429944027179:ios:89af735d1cd3182814526e',
    messagingSenderId: '429944027179',
    projectId: 'music-kuy-app',
    storageBucket: 'music-kuy-app.appspot.com',
    iosBundleId: 'com.example.musickuyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0kZJbZpLj3BH5JB7KmUIjudSxHkIWKiY',
    appId: '1:429944027179:ios:da5ab19892623fe914526e',
    messagingSenderId: '429944027179',
    projectId: 'music-kuy-app',
    storageBucket: 'music-kuy-app.appspot.com',
    iosBundleId: 'com.example.musickuyApp.RunnerTests',
  );
}
